// <auto-generated />
using MegaDeskASP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MegaDeskASP.Migrations
{
    [DbContext(typeof(MegaDeskASPContext))]
    partial class MegaDeskASPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MegaDeskASP.Models.Desk", b =>
                {
                    b.Property<int>("DeskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RushOrderDay")
                        .HasColumnType("int");

                    b.Property<int>("SurfaceMaterialID")
                        .HasColumnType("int");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DeskID");

                    b.HasIndex("SurfaceMaterialID");

                    b.ToTable("Desk");
                });

            modelBuilder.Entity("MegaDeskASP.Models.SurfaceMaterial", b =>
                {
                    b.Property<int>("SurfaceMaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SurfaceMaterialID");

                    b.ToTable("SurfaceMaterial");
                });

            modelBuilder.Entity("MegaDeskASP.Models.Desk", b =>
                {
                    b.HasOne("MegaDeskASP.Models.SurfaceMaterial", "SurfaceMaterial")
                        .WithMany("Desks")
                        .HasForeignKey("SurfaceMaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
